### ISSUE TITLE
Can the estimated variance of a Kriging model be set to 0?

### ISSUE THREAD

**Issue by dominikkirchhoff** [mbinois/GPareto#3]
Hi,

I want to apply the EGO algorithm to an application with two objectives using the EHI criterion. One objective is obtained via simulation, the other one can be computed deterministically from the inputs. In this scenario, the forumla for computing the EHI simplifies (since we know the value for the deterministic objective exactly, which basically makes the two-dimensional predictive distribution one-dimensional). However, many parts of your code would remain unchanged. I wonder if it would be sufficient if I set the deterministic relationship between the inputs and one of the outputs to be the trend of the related Kriging model and set the model’s variance to 0. Do you think this would work with the way the two-dimensional integral is computed in the package?

I messed a bit around with this idea and encountered a case where there’s a positive EHI for a dominated point, where *both* model variances have been set to 0 (the EHI should be 0 as well then). However, I’m struggling to find a minimal example that demonstrates this behavior.

Thanks in advance for your ideas on how to deal with this problem!
Dominik

**Comment by dgaudrie** [comment]
Hi Dominik,

I have never used it, but there is a "fastfun" option in GPareto. Couldn't it be the thing you want to use?

Otherwise, I am not sure setting sigma to 0 is the safest option, because it heavily relies on the C code used for computing the EHI. Imagine, you need to divide an expression by sigma...

I rapidly checked the DiceKriging package used for building the GP. You can provided ALL hyper-parameters (i.e. trend coefficient, length-scales, and variance), or you can alternatively "hack" your model after its hyper-parameters have been fitted by setting model@coef.var <- 0 and model@coef.trend <- 1. After, crit_optimizer appears to work even though the variance equals 0 (I haven't verified whether the EHI value is the correct one).

Otherwise, a first idea could be the Monte-Carlo computation of the criterion: you simulate the GP of your expensive function (Y_1) at x. Given your samples and your f_2(x), you compute and average the resulting hypervolumes.

I have not looked at it theoretically, but I believe that if you write EHI's expression and factor Y_2(x) out of the expectation, simplifications of the criterion should occur. I believe that you will find a sum and/or product of psi functions defined in Hupknes et al., 2015, "Faster Exact Algorithms for Computing Expected Hypervolume Improvement", or in Yang et al. 2016, "Preference-based multiobjective optimization using truncated expected hypervolume improvement". This could be equivalent to particular weightings of the EI criteria with regard to the expensive function only.

Last, keeping in mind that under some circumstances EHI is equivalent to a product of expected improvements with regard to a certain reference point (mEI(.;R)), in a bi-objective problem, it should not be too difficult to express the EHI as a sum (and subtractions) of mEI's with particular reference points, which would themselves reduce to particular EI weightings by factoring Y_2 out.

I hope these advises will help you finding the solution. Do not hesitate to contact me for any question,

David

**Comment by vpicheny** [comment]
Hi Dominik,
This functionality is actually implemented in GPareto: you can check 
https://www.jstatsoft.org/article/view/v089i08 (section 3.4)
In practice, this "fastfun" wrapper does exactly what you suggest: it provides a dummy model with zero variance everywhere.
Note however that the EHI is not simplified - but that shouldn't be a problem. In case of numerical issues, an alternative is to use the SMS criterion, which is basically a UCB on the HI, that is arguably more robust.
Victor

**Comment by dominikkirchhoff** [comment]
Thanks for your quick responses! I will have a look into fastfun then. :)

Dominik
